In [12]:
import numpy as np
import matplotlib.pyplot as plt 


In [13]:
# Circle 1 (radius = 5)
x = np.linspace(-5, 5, 200)  # Ensure full range for roundness
y = np.sqrt(5**2 - x**2)
x = np.hstack([x, x])  # Repeat x for upper and lower halves
y = np.hstack([y, -y])  # Reflect y to get both halves

In [14]:
x

array([-5.        , -4.94974874, -4.89949749, -4.84924623, -4.79899497,
       -4.74874372, -4.69849246, -4.64824121, -4.59798995, -4.54773869,
       -4.49748744, -4.44723618, -4.39698492, -4.34673367, -4.29648241,
       -4.24623116, -4.1959799 , -4.14572864, -4.09547739, -4.04522613,
       -3.99497487, -3.94472362, -3.89447236, -3.84422111, -3.79396985,
       -3.74371859, -3.69346734, -3.64321608, -3.59296482, -3.54271357,
       -3.49246231, -3.44221106, -3.3919598 , -3.34170854, -3.29145729,
       -3.24120603, -3.19095477, -3.14070352, -3.09045226, -3.04020101,
       -2.98994975, -2.93969849, -2.88944724, -2.83919598, -2.78894472,
       -2.73869347, -2.68844221, -2.63819095, -2.5879397 , -2.53768844,
       -2.48743719, -2.43718593, -2.38693467, -2.33668342, -2.28643216,
       -2.2361809 , -2.18592965, -2.13567839, -2.08542714, -2.03517588,
       -1.98492462, -1.93467337, -1.88442211, -1.83417085, -1.7839196 ,
       -1.73366834, -1.68341709, -1.63316583, -1.58291457, -1.53

In [15]:
# Circle 2 (radius = 10)
x2 = np.linspace(-10, 10, 400)  # More points for smoothness
y2 = np.sqrt(10**2 - x2**2)
x2 = np.hstack([x2, x2])
y2 = np.hstack([y2, -y2])

In [16]:
# Plot
plt.figure(figsize=(6,6))
plt.scatter(x1, y1, s=10, label="Circle (R=5)")
plt.scatter(x2, y2, s=10, label="Circle (R=10)", alpha=0.5)
plt.axhline(0, color="gray", linestyle="--", linewidth=0.5)
plt.axvline(0, color="gray", linestyle="--", linewidth=0.5)
plt.legend()
plt.axis("equal")  # Ensures equal scaling for roundness
plt.show()

NameError: name 'x1' is not defined

<Figure size 600x600 with 0 Axes>

In [17]:
np.vstack([y,x]).T

array([[ 0.        , -5.        ],
       [ 0.70709785, -4.94974874],
       [ 0.99745896, -4.89949749],
       [ 1.21852821, -4.84924623],
       [ 1.40344121, -4.79899497],
       [ 1.56506648, -4.74874372],
       [ 1.71002005, -4.69849246],
       [ 1.84224149, -4.64824121],
       [ 1.96430355, -4.59798995],
       [ 2.0779973 , -4.54773869],
       [ 2.18462966, -4.49748744],
       [ 2.28518935, -4.44723618],
       [ 2.38044609, -4.39698492],
       [ 2.47101324, -4.34673367],
       [ 2.55738908, -4.29648241],
       [ 2.63998503, -4.24623116],
       [ 2.71914558, -4.1959799 ],
       [ 2.79516261, -4.14572864],
       [ 2.86828607, -4.09547739],
       [ 2.93873196, -4.04522613],
       [ 3.0066885 , -3.99497487],
       [ 3.07232088, -3.94472362],
       [ 3.13577503, -3.89447236],
       [ 3.19718065, -3.84422111],
       [ 3.25665362, -3.79396985],
       [ 3.31429798, -3.74371859],
       [ 3.37020757, -3.69346734],
       [ 3.42446734, -3.64321608],
       [ 3.47715455,

In [18]:
import pandas as pd 
df1 = pd.DataFrame(np.vstack([y,x]).T,columns= ['X1','X2'])
df1['Y']=0
df2=pd.DataFrame(np.vstack([y2,x2]).T,columns = ['X1','X2'])
df2['Y']=1
df = pd.concat([df1,df2],ignore_index=True)
df.head()

X1        X2  Y
0  0.000000 -5.000000  0
1  0.707098 -4.949749  0
2  0.997459 -4.899497  0
3  1.218528 -4.849246  0
4  1.403441 -4.798995  0

In [19]:
df.tail()

X1         X2  Y
1195 -1.992442   9.799499  1
1196 -1.727688   9.849624  1
1197 -1.412431   9.899749  1
1198 -0.999997   9.949875  1
1199 -0.000000  10.000000  1

In [20]:
#independent and dependent feature 

x = df.iloc[:,:2]
y = df.Y



In [21]:
y

0       0
1       0
2       0
3       0
4       0
       ..
1195    1
1196    1
1197    1
1198    1
1199    1
Name: Y, Length: 1200, dtype: int64

In [22]:
from sklearn.model_selection import train_test_split

X_train, X_test , y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=42)

In [23]:
y_train

845     1
986     1
227     0
1192    1
671     1
       ..
1044    1
1095    1
1130    1
860     1
1126    1
Name: Y, Length: 900, dtype: int64

## Polinomial kernal 

In [24]:
#we need to find the component for polynomial kernal
#X1,X2, X1_sqaure , X2_square    X1*X2
df['X1_square'] = df['X1']**2
df['X2_square'] = df ['X2']**2 
df['X1*X2']=(df['X1']* df['X2'])
df.head()



X1        X2  Y  X1_square  X2_square     X1*X2
0  0.000000 -5.000000  0   0.000000  25.000000 -0.000000
1  0.707098 -4.949749  0   0.499987  24.500013 -3.499957
2  0.997459 -4.899497  0   0.994924  24.005076 -4.887048
3  1.218528 -4.849246  0   1.484811  23.515189 -5.908943
4  1.403441 -4.798995  0   1.969647  23.030353 -6.735107

In [25]:
x = df[['X1','X2','X1_square','X2_square','X1*X2']]
y = df["Y"]

In [26]:
X_train,x_test , y_train, y_test = train_test_split(x,y,test_size=0.25,random_state=0)

In [27]:
X_train

X1        X2  X1_square  X2_square      X1*X2
1141 -7.049337  7.092732  49.693155  50.306845 -49.999058
711   8.292369  5.588972  68.763387  31.236613  46.345823
364  -3.807175  3.241206  14.494583  10.505417 -12.339839
2     0.997459 -4.899497   0.994924  24.005076  -4.887048
1170 -5.192266  8.546366  26.959630  73.040370 -44.375008
...        ...       ...        ...        ...        ...
1033 -9.858007  1.679198  97.180294   2.819706 -16.553545
763   5.730093  8.195489  32.833965  67.166035  46.960912
835  -5.657725 -8.245614  32.009849  67.990151  46.651414
559   9.791772 -2.030075  95.878795   4.121205 -19.878033
684   9.058686  4.235589  82.059786  17.940214  38.368869

[900 rows x 5 columns]

In [28]:
import plotly.express as px 

fig = px.scatter_3d(df,x='X1',y='X2',z='X1*X2',color='Y')
fig.show()


In [29]:
fig = px.scatter_3d(df,x='X1_square',y='X2_square',z='X1*X2',color='Y')
fig.show()


In [34]:
from sklearn.svm import SVC
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [37]:
classifier = SVC(kernel="linear")

classifier.fit(X_train,y_train)

#prediction
y_pred = classifier.predict(x_test)

print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        86
           1       1.00      1.00      1.00       214

    accuracy                           1.00       300
   macro avg       1.00      1.00      1.00       300
weighted avg       1.00      1.00      1.00       300

[[ 86   0]
 [  0 214]]
1.0


In [38]:
classifier = SVC(kernel="poly")

classifier.fit(X_train,y_train)

#prediction
y_pred = classifier.predict(x_test)

print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        86
           1       1.00      1.00      1.00       214

    accuracy                           1.00       300
   macro avg       1.00      1.00      1.00       300
weighted avg       1.00      1.00      1.00       300

[[ 86   0]
 [  0 214]]
1.0


In [39]:
classifier = SVC(kernel="rbf") #radial basis kernal

classifier.fit(X_train,y_train)

#prediction
y_pred = classifier.predict(x_test)

print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        86
           1       1.00      1.00      1.00       214

    accuracy                           1.00       300
   macro avg       1.00      1.00      1.00       300
weighted avg       1.00      1.00      1.00       300

[[ 86   0]
 [  0 214]]
1.0
